// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcBj-voJhf_0jBGTsQ6kgIHOvP14MS3lM',
    appId: '1:143554999350:web:9af3bef7ea2667fc0fd497',
    messagingSenderId: '143554999350',
    projectId: 'efrei-flutter-todo',
    authDomain: 'efrei-flutter-todo.firebaseapp.com',
    storageBucket: 'efrei-flutter-todo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDPL3K96WUftidBf3zrsY-3OF0vUv4OQ',
    appId: '1:143554999350:android:1242e12ba322595d0fd497',
    messagingSenderId: '143554999350',
    projectId: 'efrei-flutter-todo',
    storageBucket: 'efrei-flutter-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkMQ4cFbAe7QxSJdZcYuJuCC6yTZBcTlU',
    appId: '1:143554999350:ios:51ab227f3f468a180fd497',
    messagingSenderId: '143554999350',
    projectId: 'efrei-flutter-todo',
    storageBucket: 'efrei-flutter-todo.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkMQ4cFbAe7QxSJdZcYuJuCC6yTZBcTlU',
    appId: '1:143554999350:ios:51ab227f3f468a180fd497',
    messagingSenderId: '143554999350',
    projectId: 'efrei-flutter-todo',
    storageBucket: 'efrei-flutter-todo.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcBj-voJhf_0jBGTsQ6kgIHOvP14MS3lM',
    appId: '1:143554999350:web:627fc51471a0ed4a0fd497',
    messagingSenderId: '143554999350',
    projectId: 'efrei-flutter-todo',
    authDomain: 'efrei-flutter-todo.firebaseapp.com',
    storageBucket: 'efrei-flutter-todo.firebasestorage.app',
  );
}
